// src/sw.js
import { precacheAndRoute } from 'workbox-precaching';

// Precaches all the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Listens for Push Notifications from your server
self.addEventListener('push', function(event) {
  const data = event.data ? event.data.json() : {};
  
  const title = data.title || 'Task Reminder';
  const options = {
    body: data.body || 'You have a pending task!',
    icon: '/pwa-192x192.png',
    badge: '/favicon.svg',
    data: {
      url: data.url || '/'
    }
  };

  event.waitUntil(self.registration.showNotification(title, options));
});

// Handles what happens when the user clicks the notification
self.addEventListener('notificationclick', function(event) {
  event.notification.close();
  event.waitUntil(
    clients.openWindow(event.notification.data.url)
  );
});